### ISSUE TITLE
check installation by rultor

### ISSUE THREAD

**Issue by nick318** [iCok/FindElementInFrames#1]
@rultor release, tag is `1.1`

**Comment by iCok** [comment]
@rultor release, tag is 1.2

**Comment by iCok** [comment]
@rultor release, tag is 1.2

**Comment by iCok** [comment]
@rultor release, tag is 1.2

**Comment by iCok** [comment]
@rultor release, tag is 1.2

**Comment by nick318** [comment]
@rultor release, tag is `1.2`

**Comment by nick318** [comment]
@rultor release, tag is `1.2`

**Comment by nick318** [comment]
@rultor release, tag is `1.2`

**Comment by nick318** [comment]
@rultor release, tag is `1.2`

**Comment by nick318** [comment]
@rultor release, tag is `1.2`

**Comment by nick318** [comment]
@rultor release, tag is `1.2`

**Comment by nick318** [comment]
@rultor release, tag is `1.2`

**Comment by nick318** [comment]
@rultor release, tag is `1.2`

**Comment by nick318** [comment]
@rultor release, tag is `1.2`

**Comment by nick318** [comment]
@rultor release, tag is `1.2`

**Comment by nick318** [comment]
@rultor release, tag is `1.2`

**Comment by nick318** [comment]
@rultor release, tag is `1.2`

**Comment by nick318** [comment]
@rultor release, tag is `1.2`

**Comment by nick318** [comment]
@rultor release, tag is `1.2`

**Comment by nick318** [comment]
@rultor release, tag is `1.2`

**Comment by nick318** [comment]
@rultor release, tag is `1.2`

**Comment by nick318** [comment]
@rultor release, tag is `1.2`

**Comment by nick318** [comment]
@rultor help

**Comment by nick318** [comment]
@rultor hello

**Comment by nick318** [comment]
@rultor stop

**Comment by nick318** [comment]
@rultor stop
