### ISSUE TITLE
FindElementInFrames sendKeys

### ISSUE THREAD

**Issue by GraemeColhoun** [iCok/FindElementInFrames#17]
Hello, 

I am new to GitHub - so please go easy. I have been having great issues interacting with BusinessObjects and iframes within it. 

Using SearchByFramesFactory, I have been able to navigate as far as clearing the text from a text field within BusinessObjects; 

SearchByFrames searchInFrame = searchFactory.search(By.xpath("//*[@id=\"D.IF1_txt\"]"));
                Optional<WebElement> elem = searchInFrame.getElem();
                elem.ifPresent(WebElement::clear);

But now I want to input text via the same method that I have just used above to clear the text. How do I utilize the same above code to sendKeys? 

Thanks in advance, 

Graeme.

**Comment by nick318** [comment]
Hi @GraemeColhoun, actually it is not a question to the library but to Java 8 usage.

You can achieve it by writing:
`elem.ifPresent(element -> element.sendKeys("test"));`

Read about functional interfaces and lambdas which were introduced in Java 8
https://www.baeldung.com/java-optional

**Comment by GraemeColhoun** [comment]
Thanks so much Nick :) Problem sorted.
